import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const work = Work_Sans({ subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
 });

export const metadata: Metadata = {
  title: "NACOS MTU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-[1440px]">
      <body>
        <Navbar />
        <div className={work.className}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
